export const queryKeys = {
  questions: (chapterId: number) => ['questions', chapterId] as const,
  questionsByChapter: (chapterId: string) => ['questions', chapterId] as const,
  quizAnswers: ['quizAnswers'] as const,
  quizAnswersByUser: (userId: string) => ['quizAnswers', userId] as const,
  answeredQuestions: (userId: string) => ['answeredQuestions', userId] as const,
  answeredQuestionsByUser: (userId: string, chapterId: number) => ['answeredQuestions', userId, chapterId] as const,
  answeredSubQuestions: (userId: string) => ['answeredSubQuestions', userId] as const,
  answeredSubQuestionsByUser: (userId: string, chapterId: number) => ['answeredSubQuestions', userId, chapterId] as const,
  subQuestions: (questionId: number) => ['subQuestions', questionId] as const,
  subQuestionsByChapter: (chapterId: string) => ['subQuestions', chapterId] as const,
  subQuestionAnswers: ['subQuestionAnswers'] as const,
  subQuestionAnswersByUser: (userId: string) => ['subQuestionAnswers', userId] as const,
  userStats: ['userStats'] as const,
  userStatsByUser: (userId: string) => ['userStats', userId] as const,
  completedChapters: (userId: string) => ['completedChapters', userId] as const,
  completedChaptersByUser: (userId: string, chapterId: number) => ['completedChapters', userId, chapterId] as const,
  invalidateAnsweredQuestions: (userId: string) => ['answeredQuestions', userId] as const,
  invalidateAnsweredSubQuestions: (userId: string) => ['answeredSubQuestions', userId] as const,
  invalidateUserStats: (userId: string) => ['userStats', userId] as const,
  invalidateSubQuestions: (questionId: string) => ['subQuestions', questionId] as const,
  quizProgress: (userId: string) => ['quizProgress', userId] as const,
  subAnswers: (userId: string, subQuestionId: number) => ['subAnswers', userId, subQuestionId] as const,
  quizRewards: (userId: string) => ['quizRewards', userId] as const,
  quizRewardHistory: (userId: string) => ['quizRewardHistory', userId] as const,
  quizRewardSettings: ['quizRewardSettings'] as const,
  quizRewardTypes: ['quizRewardTypes'] as const,
  quizRewardCategories: ['quizRewardCategories'] as const,
  quizRewardLevels: ['quizRewardLevels'] as const,
  quizRewardStatus: ['quizRewardStatus'] as const,
  quizRewardActions: ['quizRewardActions'] as const,
  quizRewardTriggers: ['quizRewardTriggers'] as const,
  quizRewardConditions: ['quizRewardConditions'] as const,
  quizRewardRules: ['quizRewardRules'] as const,
  quizRewardRuleTypes: ['quizRewardRuleTypes'] as const,
  quizRewardRuleActions: ['quizRewardRuleActions'] as const,
  quizRewardRuleConditions: ['quizRewardRuleConditions'] as const,
  quizRewardRuleTriggers: ['quizRewardRuleTriggers'] as const,
  quizRewardRuleStatus: ['quizRewardRuleStatus'] as const,
  quizRewardRuleCategories: ['quizRewardRuleCategories'] as const,
  quizRewardRuleLevels: ['quizRewardRuleLevels'] as const,
} as const; 