name: Auto Commit

on:
  schedule:
    - cron: '0 23 * * *'  # Täglich um 23:00 Uhr
  workflow_dispatch:  # Manueller Start möglich

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatischer Commit: $(date)'
          branch: main
          file_pattern: 'src/* public/* package*.json'
          commit_user_name: 'GitHub Action'
          commit_user_email: 'action@github.com'
          commit_author: 'GitHub Action <action@github.com>' 